title: Nathan Dyjack
email: ntdyjack@gmail.com
description: Statistician / Data Scientist
use_math: true
github_username:  ntdyjack

# Build settings
#theme: cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed

plugins_dir:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-remote-theme

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
